name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  repository-projects: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ghcr.io/jondotsoy/rifa-chico:latest
    - run: gh auth token | docker login ghcr.io -u jondotsoy --password-stdin
